"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.8.
Docs:
- Settings overview: https://docs.djangoproject.com/en/5.2/topics/settings/
- All settings:      https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config, Csv
from dotenv import load_dotenv

# -------------------------------------------------------------------
# Base paths & environment
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located next to manage.py
load_dotenv(BASE_DIR / ".env")

# -------------------------------------------------------------------
# Security
# -------------------------------------------------------------------
SECRET_KEY = config("SECRET_KEY", default="")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set. Add it to your .env file.")

DEBUG = config("DEBUG", default=False, cast=bool)

# Example .env:
# ALLOWED_HOSTS=127.0.0.1,localhost
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())

# Example .env:
# CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,http://localhost:8000
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "cart.apps.CartConfig",
    "orders.apps.OrdersConfig",
    "payment.apps.PaymentConfig",
    "shop.apps.ShopConfig",
]

# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -------------------------------------------------------------------
# URLs / WSGI
# -------------------------------------------------------------------
ROOT_URLCONF = "myshop.urls"
WSGI_APPLICATION = "myshop.wsgi.application"

# -------------------------------------------------------------------
# Templates
# -------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
            ],
        },
    },
]

# -------------------------------------------------------------------
# Database (SQLite for dev)
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static & Media files
# -------------------------------------------------------------------
STATIC_URL = "static/"
MEDIA_URL = "media/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session cart
CART_SESSION_ID = "cart"

# -------------------------------------------------------------------
# Celery (RabbitMQ)
# -------------------------------------------------------------------
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="")
if not CELERY_BROKER_URL:
    # safe default for local dev
    CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"

CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="rpc://")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Ensure tasks are truly async
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False

# -------------------------------------------------------------------
# Email (Yahoo SMTP)
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.yahoo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# These are your SMTP login credentials (customers do NOT see these)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")  # e.g. kudath@yahoo.co.uk
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")  # Yahoo app password

if not DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    raise RuntimeError(
        "EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set in .env for production."
    )

# IMPORTANT:
# With Yahoo SMTP, you generally cannot send as no-reply@yourdomain unless that domain is configured
# with an email provider that permits it. The reliable option is to set a friendly display name
# but keep the actual Yahoo address:
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default=(
        f"Su Solutions Shop <{EMAIL_HOST_USER}>"
        if EMAIL_HOST_USER
        else "webmaster@localhost"
    ),
)

SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

# -------------------------------------------------------------------
# Stripe
# -------------------------------------------------------------------
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_API_VERSION = config("STRIPE_API_VERSION", default="2025-11-17.clover")

if not STRIPE_PUBLISHABLE_KEY or not STRIPE_SECRET_KEY:
    raise RuntimeError("Stripe keys must be set in environment variables!")

if not STRIPE_WEBHOOK_SECRET and not DEBUG:
    raise RuntimeError("STRIPE_WEBHOOK_SECRET must be set in environment variables!")
