"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.8.
Docs:
- Settings overview: https://docs.djangoproject.com/en/5.2/topics/settings/
- All settings:      https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from decouple import config
from dotenv import load_dotenv

# -------------------------------------------------------------------
# Base paths & environment
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env located next to manage.py
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    """Parse boolean-like environment variables robustly."""
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "t", "yes", "y"}


# -------------------------------------------------------------------
# Security
# -------------------------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set. Add it to your .env file.")

DEBUG = env_bool("DEBUG", default=False)

_raw_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]

if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

_raw_csrf = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf.split(",") if o.strip()]


# -------------------------------------------------------------------
# Applications
# -------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "cart.apps.CartConfig",
    "orders.apps.OrdersConfig",
    "payment.apps.PaymentConfig",
    "shop.apps.ShopConfig",
]


# -------------------------------------------------------------------
# Middleware
# -------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -------------------------------------------------------------------
# URLs / WSGI
# -------------------------------------------------------------------
ROOT_URLCONF = "myshop.urls"
WSGI_APPLICATION = "myshop.wsgi.application"


# -------------------------------------------------------------------
# Templates
# -------------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
            ],
        },
    },
]


# -------------------------------------------------------------------
# Database (SQLite for dev)
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"  # switch to "Europe/London" if you want
USE_I18N = True
USE_TZ = True


# -------------------------------------------------------------------
# Static & Media files
# -------------------------------------------------------------------
STATIC_URL = "static/"
MEDIA_URL = "media/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session cart
CART_SESSION_ID = "cart"


# -------------------------------------------------------------------
# Celery (RabbitMQ)
# -------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")

if not CELERY_BROKER_URL and not DEBUG:
    raise RuntimeError("CELERY_BROKER_URL is not set. Add it to your .env file.")

if not CELERY_BROKER_URL and DEBUG:
    CELERY_BROKER_URL = "amqp://guest:guest@localhost:5672//"

CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "rpc://")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False


# -------------------------------------------------------------------
# Email (Yahoo SMTP)
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.yahoo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# These are your SMTP login credentials (customers do NOT see these)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")  # e.g. kudath@yahoo.co.uk
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # Yahoo app password

if (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD) and not DEBUG:
    raise RuntimeError(
        "EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set in .env for production."
    )

# What customers SEE as the sender (hide your personal email)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Su Solutions Shop <no-reply@susolutions.shop>",
)

# Used for error emails; keep it non-personal too
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)


# -------------------------------------------------------------------
# Stripe
# -------------------------------------------------------------------
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

STRIPE_API_VERSION = os.getenv("STRIPE_API_VERSION", "2025-11-17.clover")

if not STRIPE_PUBLISHABLE_KEY or not STRIPE_SECRET_KEY:
    raise ValueError("Stripe keys must be set in environment variables!")

if not STRIPE_WEBHOOK_SECRET and not DEBUG:
    raise ValueError("STRIPE_WEBHOOK_SECRET must be set in environment variables!")
